spring:
  application:
    name: movie-info
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/movieinfo
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
movie-api:
  omdb-base-url: https://www.omdbapi.com/
  omdb-key: ${OMDB_API_KEY}
  tmdb-base-url: https://api.themoviedb.org/
  tmdb-key: ${TMDB_API_KEY}