apiVersion: v1
kind: Secret
metadata:
  name: movie-info-secrets
type: Opaque
data:
  mysql-root-password: {{ .Values.movieInfo.env.mysqlRootPassword | b64enc | quote }}
  mysql-password: {{ .Values.movieInfo.env.mysqlPassword | b64enc | quote }}
  mysql-replication-password: {{ .Values.movieInfo.env.mysqlPassword | b64enc | quote }}
  redis-password: {{ .Values.movieInfo.env.redisPassword | b64enc | quote }}
  omdb-api-key: {{ .Values.movieInfo.apiKeys.omdb | b64enc | quote }}
  tmdb-api-key: {{ .Values.movieInfo.apiKeys.tmdb | b64enc | quote }}
